sudo: false
language: go
go:
  - "1.11.1"
services:
  - "docker"

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
  # - bash scripts/gogetcookie.sh
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/golang/lint/golint
  - go get github.com/golang/dep/cmd/dep
  - go get github.com/go-critic/go-critic/...

script:
  - make test
  - make vendor-status
  - make importscheck
  - make lintcheck
  - make vet
  - make critic
  - make website-test

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
