sudo: false
language: go
go:
  - "1.10.1"
install:
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/golang/lint/golint
script:
  - make fmtcheck
  - make importscheck
  - make lintcheck
  - make vetcheck
